#!/bin/sh
#
# Filename: mkiso
# Author: Olivier Sirol <czo@free.fr>
# License: GPL-2.0 (http://www.gnu.org/copyleft)
# Description: Build an isofs from a rescue cd


DIRNAME="$(dirname $(readlink -f $0))"
NAME="${DIRNAME##*/}"
ISO_PUBLISHER="Czo-System-Rescue <https://gitlab.com/czo/czo-system-rescue>"
ISO_APPLICATION="Czo-System-Rescue"

echo "$DIRNAME"
echo "$NAME"
cd $DIRNAME

rm -f ../$NAME.iso

xorriso \
    -as mkisofs \
    -iso-level 3 \
    -full-iso9660-filenames \
    -volid RESCUE811 \
    -publisher "$ISO_PUBLISHER" \
    -appid "$ISO_APPLICATION" \
    -isohybrid-mbr isolinux/isohdpfx.bin \
    -eltorito-boot isolinux/isolinux.bin \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        -eltorito-catalog isolinux/boot.cat \
    -eltorito-alt-boot \
        -e EFI/archiso/efiboot.img \
        -no-emul-boot \
        -isohybrid-gpt-basdat \
    -o ../$NAME.iso .

## change live (must be run as root)
# ( mkdir czo-sysrcd-811 && cd czo-sysrcd-811 && bsdtar -xf ../czo-sysrcd-811.iso && cd .. && unsquashfs czo-sysrcd-811/sysresccd/x86_64/airootfs.sfs )
## make changes: remove my dotconfigs (ok, there too much aliases ;-), configure .ssh/authorized_keys and so on... then:
# ( cd czo-sysrcd-811/sysresccd/x86_64 && rm airootfs.sfs; mksquashfs ../../../squashfs-root airootfs.sfs -comp xz -Xbcj x86 -b 512k -Xdict-size 512k && sha512sum airootfs.sfs > airootfs.sha512 && cd ../.. && ./mkiso )

